save docker image

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -85,22 +85,22 @@ jobs:
     steps:
       - checkout
       - run: 
-        name: Build Image
-        command: |
-          TAG=$DCKUSER/capstone
-          docker build --tag=$TAG .
-          echo $DCKPWD | docker login -u $DCKUSER --password-stdin
-          docker run -d -p 8001:8000 $TAG
-          sleep 10
-          echo "Running check after docker run"
-          check=`curl -s localhost:8001 | grep -c "^Simple Flask"`
-          echo "Check result: "$check
-          if [ 1 -ne $check ]; then echo "Post check build failed";exit 1;fi
+          name: Build Image
+          command: |
+            TAG=$DCKUSER/capstone
+            docker build --tag=$TAG .
+            echo $DCKPWD | docker login -u $DCKUSER --password-stdin
+            docker run -d -p 8001:8000 $TAG
+            sleep 10
+            echo "Running check after docker run"
+            check=`curl -s localhost:8001 | grep -c "^Simple Flask"`
+            echo "Check result: "$check
+            if [ 1 -ne $check ]; then echo "Post check build failed";exit 1;fi
       - run:
-        name: Save image to an archive
-        command: |
-          mkdir docker-image
-          docker save -o docker-image/image.tar capstoneAppImage
+          name: Save image to an archive
+          command: |
+            mkdir docker-image
+            docker save -o docker-image/image.tar capstoneAppImage
       - persist_to_workspace:
           root: .
           paths:
